### ISSUE TITLE
how test？

### ISSUE THREAD

**Issue by Shuo-Jia** [1995parham/krtp#2]
Thank you！I don't know how to run it

**Comment by 1995parham** [comment]
Hello, for running and using this library you can use following code:

```
const RTPSession = require('krtp').RTPSession

const s = new RTPSession(1373)

s.on('message', (msg) => {
  console.log(msg)
  s.close()
})

s.send(Buffer.from('Hello world'))
```

in `on` you provide a handler for data chunks that are received and with `send` function you send data to your endpoint. in reality one side just sends data and one side just receives.

**Comment by Shuo-Jia** [comment]
OK,Thank you very much
