### ISSUE TITLE
Incorrect deserialization bit mask for CC

### ISSUE THREAD

**Issue by jneuendorf-i4h** [1995parham/krtp#23]
Hi,

while looking through your library, I think I found an error here: 

https://github.com/1995parham/krtp/blob/37a2e967d6ec6c00ab373fc4bbf76571bbad7376/lib/Packet.ts#L74

This reads 5 bits (`0x1f == 0b00011111`) instead of just the 4 bits (`0x0f == 0b00001111`) that CC has.

**Comment by 1995parham** [comment]
Hi, I think you are right. Can you please create an MR? I can also do it by myself.
