### ISSUE TITLE
Missing lib folder after install package

### ISSUE THREAD

**Issue by iagoccampos** [1995parham/krtp#7]
Hi. 

The index.ts files import everything from the lib folder, but there is no lib folder! The lib folder exists on your project, but not on the package.

**Comment by iagoccampos** [comment]
It seems to be that the .npmignore is blocking the folder to be downloaded.

**Comment by 1995parham** [comment]
Yes, you are right, I will remove it now and release a new version.

**Comment by 1995parham** [comment]
I have updated the packages and create a new release.
